apiVersion: apps/v1
kind: Deployment

metadata:
  name: reg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    containers:
    - image: ../backend/
