name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install deps
      run: pip install -r ./backend/requirements.txt
    - name: Lint for PYTHON
      run: flake8 ./backend/main.py
    - name: Lint for NGINX
      run: nginx -t

